### ISSUE TITLE
Blank pdf download

### ISSUE THREAD

**Issue by martadove** [Leone25/kitaboo-downloader#34]
I followed every step of the guide and seemed to have no problem with it, but when I open the downloaded .pdf file in the directory, every single page is blank. 
This is what I see on the terminal:
![Screenshot 2024-06-19 174432](https://github.com/Leone25/kitaboo-downloader/assets/173252003/4a8fe4d4-2813-4c49-8bd8-24f7aff77589)

Does anybody have a solution?

**Comment by Leone25** [comment]
unfortunately all the books that i used to have on kitaboo have expired so i can't test if the script is still working, but assuming it is, that error generally means that you entered something wrong

**Comment by XenoXsX** [comment]
I tried at least 6 times. I get the same error.

**Comment by Leone25** [comment]
Well perhaps then something updated, dm me on twitter (same name + 03) perhaps i can try to figure it out...

**Comment by einsteniano4000** [comment]
Hai risolto? Ho lo stesso problema (sto usando linux, l'applicazione python funziona perfettamente mentre questa node.js mi dà lo stesso errore di svg). Grazie.

**Comment by Leone25** [comment]
Nessuno mi ha contattato in privato quindi sono sono riuscito ancor a risolvere

**Comment by Leone25** [comment]
Great news everyone! I've updated the script and it now is working again!
Please download the repo again, and follow the new instructions.

One side note, I've removed support for non encrypted books because I couldn't find one, so either they are as common as unicorns or I was just unlucky. If someone has issues again, it's probably because of that, so please reach back by opening a new issue and I can try to figure it out.

## For the technically curious people
### The origin: 
This was actually something I kinda knew would happen at some point, ever since encrypted books got introduced I couldn't figure out how to get the encryption key, because it self was encrypted. This was originally worked around by "abusing" of a mistake made by developers of zanichelli that exposed a variable that contained the raw encryption key, thus it was easy to just grab that and run with it.
### What happened?
Whatever magic update happened, it got rid of the exposed variable, it's as easy as that, the system it self didn't change.
### Why didn't it work before and it does now?
Perseverance. Originally I had already figured out that the encryption key was encrypted with an RSA methodology, and I could easily reproduce it using [a website I found](https://anycript.com/crypto/rsa). I issue was that I couldn't get any library to work in node.js to do the same thing programmatically. I'm not sure what library the web reader or the website I found used, but what I know is that they didn't really care if the key was formatted correctly, all they needed was the main body. Meanwhile, on node.js to be able to make it work, I used the standard crypto module, which turns out to be very finicky about formatting the key correctly. A bit of headbanging on that and the rest was pretty standard.

I hope you found that whole story as much fun as I did, tho tbh I would rather not do it again lol

Have fun, and download responsibly!
Rico
